"""Recreate Music 5

Revision ID: e5ef02350ae5
Revises: edee9f2458f2
Create Date: 2024-05-15 20:33:28.488850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ef02350ae5'
down_revision: Union[str, None] = 'edee9f2458f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_songs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    op.drop_table('favourite_songs')
    op.add_column('albums', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('albums', 'descriptions')
    op.add_column('artists', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('artists', 'descriptions')
    op.add_column('songs', sa.Column('album_id', sa.Integer(), nullable=False))
    op.drop_constraint('songs_aldum_id_fkey', 'songs', type_='foreignkey')
    op.create_foreign_key(None, 'songs', 'albums', ['album_id'], ['id'])
    op.drop_column('songs', 'aldum_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('aldum_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.create_foreign_key('songs_aldum_id_fkey', 'songs', 'albums', ['aldum_id'], ['id'])
    op.drop_column('songs', 'album_id')
    op.add_column('artists', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'description')
    op.add_column('albums', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('albums', 'description')
    op.create_table('favourite_songs',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name='favourite_songs_song_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favourite_songs_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'song_id', name='favourite_songs_pkey')
    )
    op.drop_table('favorite_songs')
    # ### end Alembic commands ###
